name: streamlit2
channels:
  - conda-forge
  - bioconda
dependencies:
  - _openmp_mutex=4.5
  - altair=5.4.1
  - appnope=0.1.4
  - asttokens=3.0.0
  - attrs=24.2.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.14
  - aws-c-common=0.9.19
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.8
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.9
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.9
  - aws-sdk-cpp=1.11.329
  - backcall=0.2.0
  - backports=1.0
  - backports.zoneinfo=0.2.1
  - blinker=1.8.2
  - blosc=1.21.5
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - c-blosc2=2.12.0
  - ca-certificates=2026.1.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.0
  - certifi=2024.8.30
  - cffi=1.17.0
  - charset-normalizer=3.4.0
  - colorama=0.4.6
  - comm=0.2.2
  - conda=22.9.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.11.0
  - contourpy=1.1.1
  - cryptography=41.0.7
  - cycler=0.12.1
  - debugpy=1.8.5
  - decorator=5.1.1
  - dill=0.3.9
  - executing=2.1.0
  - fmt=9.1.0
  - fonttools=4.53.1
  - freetype=2.12.1
  - gflags=2.2.2
  - gitdb=4.0.11
  - gitpython=3.1.43
  - glog=0.7.1
  - h2=4.1.0
  - h5py=3.11.0
  - hdf5=1.14.3
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib-resources=6.4.5
  - importlib_resources=6.4.5
  - ipykernel=6.29.5
  - ipython=8.12.2
  - ipywidgets=8.1.5
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyterlab_widgets=3.0.13
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.4
  - libarchive=3.6.2
  - libarrow=16.1.0
  - libarrow-acero=16.1.0
  - libarrow-dataset=16.1.0
  - libarrow-substrait=16.1.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.8.0
  - libcxx=21.1.8
  - libdeflate=1.20
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgoogle-cloud=2.24.0
  - libgoogle-cloud-storage=2.24.0
  - libgrpc=1.62.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmamba=1.5.0
  - libmambapy=1.5.0
  - libnghttp2=1.58.0
  - libopenblas=0.3.25
  - libparquet=16.1.0
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libsolv=0.7.29
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libwebp-base=1.6.0
  - libxcb=1.15
  - libxml2=2.12.7
  - libzlib=1.2.13
  - llvm-openmp=21.1.8
  - llvmlite=0.41.1
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.5.0
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib=3.7.3
  - matplotlib-base=3.7.3
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mizani=0.9.3
  - munkres=1.1.4
  - narwhals=1.13.3
  - natsort=8.4.0
  - ncls=0.0.68
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numba=0.58.1
  - numexpr=2.8.4
  - numpy=1.24.4
  - openjpeg=2.5.2
  - openssl=3.6.0
  - orc=2.0.1
  - packaging=24.2
  - pandarallel=1.6.5
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - plotly=5.24.1
  - plotnine=0.12.4
  - pooch=1.8.2
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - protobuf=4.25.3
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-cpuinfo=9.0.0
  - pyarrow=16.1.0
  - pyarrow-core=16.1.0
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.22
  - pydeck=0.8.0
  - pygments=2.18.0
  - pyopenssl=23.2.0
  - pyparsing=3.1.4
  - pyranges=0.1.4
  - pysocks=1.7.1
  - pytables=3.8.0
  - python=3.8.19
  - python-dateutil=2.9.0
  - python-ternary=1.0.8
  - python-tzdata=2024.2
  - python_abi=3.8
  - pytz=2024.2
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - re2=2023.09.01
  - readline=8.3
  - referencing=0.35.1
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - requests=2.32.3
  - rich=13.9.4
  - rpds-py=0.20.0
  - ruamel_yaml=0.15.80
  - scikit-learn=1.3.2
  - scipy=1.10.1
  - setuptools=75.3.0
  - six=1.16.0
  - smmap=5.0.0
  - snappy=1.2.2
  - sorted_nearest=0.0.39
  - sparse=0.15.5
  - sqlite=3.46.0
  - stack_data=0.6.2
  - statsmodels=0.14.1
  - streamlit=1.41.1
  - tabulate=0.9.0
  - tenacity=9.0.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - toml=0.10.2
  - toolz=1.0.0
  - tornado=6.4.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025c
  - tzlocal=5.2
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - watchdog=4.0.1
  - wcwidth=0.2.13
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstandard=0.23.0
  - zstd=1.5.6
  - pandas=1.5.3
  - pip:
    - anndata==0.9.2
    - click==8.1.3
    - exceptiongroup==1.3.1
    - fpdf==1.7.2
    - get-annotations==0.1.2
    - iniconfig==2.1.0
    - networkx==3.1
    - patsy==1.0.2
    - pluggy==1.5.0
    - pynndescent==0.5.13
    - pytest==8.3.5
    - scanpy==1.9.8
    - seaborn==0.13.2
    - session-info==1.0.1
    - stdlib-list==0.10.0
    - tomli==2.3.0
    - umap-learn==0.5.7
